---
- DCUF System Information Document in Declarative format:
  - DCUF System Description :
      System Name variable (SYSNAME):  DCUF
      System Clone variable (SYSCLONE):  DF
      SYS2 or SYSACS HLQ:    SYS2  
      System Description:    Atos Factory System
  - System Software :
    - Base Control Program : 
        Version : 2.4
        FMID:   HBB77C0
        JES (2 or 3) :  JES2   
        Node :  ADAJES0F   
    -  Security package : 
         Software : RACF
         Version :  2.4 
    - CICS Level: 7.2.0
  - System Catalog Structure : 
       Master catalog:  SYS1.MCATZS24.DCUF
       Volume:  X24CT1
  - User Catalogs:
     - SYS1.ZS24.MCAT       
     - SYS1.ZS23.MCAT       
     - SYS1.ZS22.MCAT        
     - SYS1.ZS21.MCAT        
     - SYS1.ZS1D.MCAT        
     - SYS1.VOLCAT.VF        
     - SYS1.USERCAT.DCUF     
     - SYS1.UCAT.ZS24DS.SMPE 
     - SYS1.UCAT.ZS24DF.SMPE
     - SYS1.UCAT.ZS23DS.SMPE 
     - SYS1.UCAT.ZS23DF.SMPE 
     - SYS1.UCAT.ZS22ST.SMPE 
     - SYS1.UCAT.ZS22DS.SMPE 
     - SYS1.UCAT.ZS22DF.SMPE 
     - SYS1.UCAT.ZS21DS.SMPE 
     - SYS1.UCAT.ZS21DF.SMPE 
     - SYS1.UCAT.ZS1DDS.SMPE 
     - SYS1.UCAT.ZS1DDF.SMPE 
     - SYS1.UCAT.SYSSOT      
     - SYS1.UCAT.DCUF        
     - SYS1.TSTPLX1.UCAT  
     - SYS1.MCATZS24.DISTZOS   
     - SYS1.MCATZS23.DISTZOS 
     - SYS1.MCATZS22.DISTZOS   
     - SYS1.MCATZS22.DCUF      
     - SYS1.MCATZS21.DISTZOS   
     - SYS1.MCATZS21.DCUF      
     - SYS1.MCATZS1D.ONEPACK   
     - SYS1.MCATZS1D.DISTZOS   
     - SYS1.MCATZS1D.DCUF      
     - SYS1.VOLCAT.VGENERAL    
     - SYS1.VOLCAT.VF
     - SYS1.UCAT.TSGNS         
     - SYS1.UCAT.TSGVS         
     - SYS1.MCATZS23.DCUF
     - SYS1.MCATZS24.DCUF 

  - ALIASES :
     - vsam : ACSNS
       Catalog : SYS1.UCAT.TSGNS
     - Non VSAM : ACSVS
       Catalog : SYS1.UCAT.TSGVS
  - System Startup Parameter libraries :
     - SYS1.PARMLIB :  
         Volume : X24CT1
     - SYS0.IPLPARM :
         Volume :   IRVIOD
     - Active Member : LOAD24
  - User User modification jobs for Parameter libraries:
       Source: SYS2.SOURCE.DCUF
       Staging:  SYS2.STAGELIB.DCUF
  - PARMLIB User Modification Jobs in relation to PARAMETER member :
      PROGDF : ZOSXF01 
      SCHEDDF : ZOSXF03 
      IEFSSNDF : ZOSXF04 
      IEASVCDF : ZOSXF05 
      IEASYSDF : ZOSXF06 
      COMMNDDF : ZOSXF07 
      CEEPRMDF : ZOSXF08 
      HZSPRMDF : ZOSXF09 
      MPFLSTDF : ZOSXF10 
      SMFPRMDF : ZOSXF11 
      LPALSTDF : ZOSXF12 
      CONSOLDF : ZOSXF13 
      IKJTSO00 : ZOSXF14 
      TSOKEY00 : ZOSXF15 
      SMFPRMXT : ZOSXF16 
      IECIOSDF : ZOSXF18 
      IGDSMSDF : ZOSXF19 
      VATLSTDF : ZOSXF20 
      IEASLPDF : ZOSXF21 
      IPCSPR00 : ZOSXF23 
      DEVSUPDF : ZOSXF24 
      IEACMD00 : ZOSXF25   
      IEAOPTDF : ZOSXF26   
      COFVLFDF : ZOSXF27   
      IEALPADF : ZOSXF28   
      IEADMR00 : ZOSXF31   
      CSVLLADF : ZOSXF32   
      APPCPMDF : ZOSXF33   
      ERBRMF00 : ZOSXF34   
      IEAPAKDF : ZOSXF35 
      IEAFIXDF : ZOSXF36     
      DIAGDF : ZOSXF37
      MMSLSTDF : ZOSXF40
      COFDLFDF : ZOSXF41
      PFKTABDF : ZOSXF43
      GRSCNFDF : ZOSXF44
      COUPLESX : ZOSXF45
      COUPLEDF : ZOSXF46
      CNGRPDF : ZOSXF47
      MSTJCLDF : ZOSXF48
      ADYSET00 : ZOSXF49
      IFAPRDDF : ZOSXF50
      ALLOCDF : ZOSXF51
      IEADMP00 : ZOSXF52
      IEAAPP00 : ZOSXF53
      IEASYMDF : ZOSXF54
      BPXPRM00 : ZOSXF55
      BPXPRMDF : ZOSXF56
      CLOCKCD : ZOSXF57
      CLOCKCS : ZOSXF58
      ASCHPMDF : ZOSXF59
      IEAABD00 : ZOSXF60
      CUNUNIDF : ZOSXF75
      CUNIMGDF : ZOSXF76
      AUTOMSTR : ZOSXF77
      AMTMAPU : ZOSXF78
      COMMNDIF : ZOSXF79
      ALLOCDF : ZOSXF80
      IOEFSPRM : ZOSXF81
      CSQ7IPCS : ZOSXF82
      PROGDF : ZOSXF83
  - Operating System Exits for DCUF :
    - CICS EXIT :  
       module : DFHHPSVC
       User Mod :  ZOSC040
       Loadlib : SYS1.NUCLEUS
    - DADSM EXIT :  
       module : IGGPRE00
       User Mod :  ZOSM008
       Loadlib : SYS1.LPALIB
    - LE EXIT :  
       module : CELQXTAN
       User Mod :   ZOSM015
       Loadlib : SYS1.CEE.SCEERUN2
  - LE EXIT :  
       Module: CEEEXTAN
       User Mod :  ZOSM016
       Loadlib :  SYS1.CEE.SCEERUN # LE Abnormal Termination User exit
  - IMS Type 4 SVC :  
       Module : IGC0025E
       User Mod : ZOSM017
       Loadlib : SYS1.LPALIB
  - REXX EXIT1 : 
       Module  : IRXCMPTM
       User Mod :   ZOSM020
       Loadlib : SYS1.LINKLIB # TSO/E REXX Compiler Programming Table
  - REXX EXIT2 : 
       Module : EAGCML
       User Mod :   ZOSM025
       Loadlib : SYS1.LINKLIB # TSO/E REXX Compiler Programming Table
  - REXX Exit3 :  
       Module : IGC250
       User Mod : ZOSM040
       Loadlib : SYS1.NUCLEUS
  - ADRDSSU EXIT : 
       Module : ADRUENQ 	   
       User Mod : ZOSM045
       Loadlib : SYS1.LINKLIB(ADRDSSU) # ADRUENQ MODULE FOR ADRDSSU
  - SMF EXIT :  
       Module  : VBSFIX
       User Mod : ZOSM243
       Loadlib : SYS2.LINKLIB # THIS USERMOD IS FOR VBSFIX
  - SMF EXIT :  
       Module : SMFDUMP
       User Mod :   ZOSM244
   - Loadlib : SYS2.LINKLIB # SMFDUMP ROUTINE TO DUMP SYS1.MANX DATASETS
  - SMF EXIT :  
       Module : SPANCOPY
       User Mod : ZOSM245
       Loadlib : SYS2.LINKLIB # SMF COPIES AND CLEANS A SPANNED RECORD FILE
  - SMF EXIT :  
       Module : IEFU29
       User Mod :  ZOSM247
       Loadlib :   #SMF SWITCH ROUTINE 
  - SMF EXIT :  
       Module : IEFACTRT
       user mod : ZOSM248
       Loadlib :   SYS1.LPALIB # SMF TERMINATION EXIT
  - xxx   :  
       Module : ISPCFIGU 
       user mod : ZOSM256
       Loadlib :   
  - xxxx  : 
       Module : ICHPWX01 
       User Mod : ZOSRF01
       Loadlib : xxx  
  - RMM :  
       Module : EDGCVRSL 
       User Mod : ZOSMRMM
       Loadlib : xxxx  
  - RACF EXIT :  ICHRIN03
   - User Mod :  ZOSR010
   - Loadlib : SYS1.LPALIB  # RACF STARTED PROCUDURE  
  -   : ICHRFR01
   - User Mod :  ZOSR012
   - Loadlib :  SYS2.LINKLIB # RACF ROUTER
  -   :  ICHRRCDE
   - User Mod :   ZOSR015
   - Loadlib :  SYS2.LINKLIB # RACF CLASS DESCRIPTOR
  - JES2 Exit :  HASX05C
   - User Mod :  ZOSJ005
   - Loadlib : SYS2.LINKLIB

 - SVC’s in Use
  - HPO SVC
   - SVC Number :   0219 (DB)
   - Dynamic/Static :  Static 
   - User Mod :  ZOSC040 
   - Location :   E-RWNUC
   - Module :  DFHHPSVC
  - CICS SVC
   - SVC Number :   0220 (DC)
   - Dynamic/Static :  Static 
   - User Mod :  Pending 
   - Location :   E-PLPA
   - Module :  DFHCSVC
  - IMS TYPE 2
   - SVC Number :   0250 (FA)
   - Dynamic/Static :  Static 
   - User Mod :  ZOSM040 
   - Location :   RWNUC
   - Module :  IGC250
  - IMS TYPE 4 (LPA)
   - SVC Number :   0255 (FF)
   - Dynamic/Static :  Static 
   - User Mod :  ZOSM017 
   - Location :   E-PLPA
   - Module :  IGC0025E

 - JES2 Information
  - Spool :  SYS1.DCUF.HASPACE
   - Volume :  DFSPL*
  - Checkpoint1 : SYS1.DCUF.HASPCKP1
   - Volume : DFHCD4    
  - Checkpoint2 : SYS1.DCUF.HASPCKP2
   - Volume :  DFHCD3
  - JES2 Parameter Library
   - Parmlib :  SYS2.PARMLIB
   - Volume :  X24CT1
   - Deck
    - COMMONDF 
    - COMNETDF 
    - COMPRTDF 
    - COMSYSDF 
    - GTFVTAM  
    - ISFPRM01 
    - JES3IN00 
    - JFIXDF   
  - JES2 User Exits
   - Exit Number :  5
    - Module  : HASX05C
    - Routine : HASX5CTR  
    - User Mod  : ZOSJ005
    - Source  : SYS2.SOURCE.DCUF
  - JES2 Procedure Libraries
   - Proc : PROC00  
    - SYS1.PROCLIB 
     Volume : X24RA1
    - SYS2.PROCLIB 
     Volume : X24CT1 
    - SYS2.PROCLIB.DCUF
                          Volume : X24CT1 
    - SYS2.PROCLIB.ZS24
     Volume : X24CT1
    - SYS2.CICSMQ.PROCLIB.DCUF
     Volume : SYSPK5
    - SYS2.TSO.PROCLIB.DCUF
     Volume : X24CT1

 - TSO Access
  - VTPACS :  TSODCUF
  - Logon ID Format :  SYS###  
 - TSO Logon Procedures
  - Systems :
   - Procedure :  SYSUSER
   - Library : SYS2.TSO.PROCLIB.DCUF
   - Volume :   X24CT1
  - Disaster
   - Procedure : DRPROC
   - Library : SYS2.TSO.PROCLIB.DCUF
   - Volume : X24CT1
  - User
   - Procedure :
   - Library :
   - Volume :
 - CA-View (SAR) Access (Or other spool collection product)
  - Spool Collection SW : SAR
  - Command :  SARDCUF
 - Local Libraries
  - Stagelib
   - SYS2.STAGELIB.DCUF
    - Volume : X24CT1
  - Source
   - SYS2.SOURCE.DCUF
    - Volume : X24CT1
  - Proclib
   - SYS2.PROCLIB.DCUF
    - Volume : X24CT1
  - LoadLib
   - SYS2.LINKLIB.DCUF
    - Volume : X24RA1
  - Jobcards 
   - Source : SYS2.STAGELIB.DCUF
   - Member : JOBCARD
  - Tables
   - Target : SYS2.TABLES
 - Operating System Deviations
  - Examples
   - Utilizing different naming conventions than described in the procedures 
   - Using different catalogs than recommended in the procedure
   - Using a different SMP/E environment setup than documented in the System procedures 
   - Any novelty situation installed, or in place for this client that requires consideration when upgrading the system. 
  - Deviation1 |
     As DCUF is a TEST system and holds multiple Operating Systems simultaneously (at present it holds  z/OS V2.2, z/OS V2.3 and z/OS V2.4), 
    it is not feasible to meet the volume naming standards on it. To differentiate between z/OS V2.2, z/OS V2.3 and z/OS V2.4 volumes 
    (also called as suites) the volumes are initialized as follows.
 SMP/E Environment
  For z/OS V2.2:
   RES volumes :  X22Rxn # where x is suite name and n is sequence no., e.g. X22RA1 / X22RB1
   DLIB volumes : X22Dxn   
   USS volumes :  X22Oxn
   CATALOG volume : X22CT1
   Product volume :  X22SY1
   SMPE volume :  X22PE1
   MCAT  :   SYS1.MCATZS22.DCUF
   SMPE HLQ :   SMPE.ZS22M9.R2006.**
  For z/OS V2.3:
   RES volumes :  X23Rxn #where x is suite name and n is sequence no., e.g. X23RA1 / X23RB1
   DLIB volumes : X23Dxn   
   USS volumes :  X23Oxn
   CATALOG volume : X23CT1
   Product volume : X23SY1
   SMPE volume :  X23PE1
   MCAT  :   SYS1.MCATZS23.DCUF
   SMPE HLQ :   SMPE.ZS23M9.R2006.**
  For z/OS V2.4 : 
   RES volumes :  X24Rx1 # where x is suite name ., e.g. X24RA1 / X24RB1
   DLIB volumes : X24Dx1   
   USS volumes : X24Ox1
   CATALOG volume : X24CT1
   Product volume : X24SY1
   SMPE volume :  X24PE1
   MCAT  :   SYS1.MCATZS24.DCUF
   SMPE HLQ :   SMPE.ZS24M27.R2006.**
 SMP/E Global Zones :
  Global :  SMPE.ZS24M27.R2006.GLOBAL.CSI
  Target :  SMPE. ZS24M27.R2006.TARGET.CSI
  Distribution Library: SMPE. ZS24M27.R2006.DLIB.CSI
  Proc  : SYS2.PROCLIB.DCUF(SMPEZS24)
  Active Suite :  “A” Suite
  Alternate Suite :  “B” Suite
 Non/SMPE Installed Software :
  DBS :
   Vendor :  ROCKETSOFTWARE
   Qualifier :  ACSNS.DBS.**
   Maintainer : zSeries
  IBMTOOLS :
   Vendor :  IBM
   Qualifier :  ACSNS.IBMTOOLS.**
   Maintainer : zSeries

 Document Change Control :
  First Created On :  
  First Creator : 
  Last Revised On :  
  Last Revised by :  

